ServerEvents.recipes(craftlin => {
    console.log('Initializing Mystical Agriculture.js!')
    craftlin.replaceInput({ input: 'mysticalagriculture:machine_frame'}, 'mysticalagriculture:machine_frame', 'industrialforegoing:machine_frame_simple')
    craftlin.shaped(Item.of('industrialforegoing:dryrubber', 2), ['RRR', 'R R', 'RRR'], { R: 'mysticalagriculture:rubber_essence' })
    craftlin.shaped(Item.of('extendedae:entro_crystal', 4), ['EEE', 'E E', 'EEE'], { E: 'mysticalagriculture:entro_crystal_essence' })
    craftlin.shaped(Item.of('mysticalagriculture:soul_dust', 1), ['SSS', 'SSS', 'SSS'], { S: 'mysticalagriculture:soulium_essence' })
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_blue', 8), ['X X', ' X ', 'X X'], { X: 'mysticalagriculture:xychorium_essence' })
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_green', 8), ['XXX', 'XX ', '   '], { X: 'mysticalagriculture:xychorium_essence' })
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_red', 8), ['   ', ' XX', 'XXX'], { X: 'mysticalagriculture:xychorium_essence' })
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_dark', 8), ['XX ', 'XX ', 'X  '], { X: 'mysticalagriculture:xychorium_essence' })
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_light', 8), ['X  ', 'XX ', 'XX '], { X: 'mysticalagriculture:xychorium_essence' })
    craftlin.shaped(Item.of('ae2:silicon', 4), ['SSS', 'S S', 'SSS'], { S: 'mysticalagriculture:silicon_essence' })
    console.log('Mystical Agriculture.js is loaded!')
})