console.log('Initializing Mystical Agriculture.js!')
ServerEvents.recipes(craftlin => {
    craftlin.replaceInput({ input: 'mysticalagriculture:machine_frame'}, 'mysticalagriculture:machine_frame', 'industrialforegoing:machine_frame_simple')
    craftlin.shaped(Item.of('industrialforegoing:dryrubber', 2), ['RRR', 'R R', 'RRR'], { R: 'mysticalagriculture:rubber_essence' }).id('craftlin:mystical/dryrubber')
    craftlin.shaped(Item.of('extendedae:entro_crystal', 4), ['EEE', 'E E', 'EEE'], { E: 'mysticalagriculture:entro_crystal_essence' }).id('craftlin:mystical/entro_crystal')
    craftlin.shaped(Item.of('mysticalagriculture:soul_dust', 1), ['SSS', 'SSS', 'SSS'], { S: 'mysticalagriculture:soulium_essence' }).id('craftlin:mystical/soul_dust')
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_blue', 8), ['X X', ' X ', 'X X'], { X: 'mysticalagriculture:xychorium_essence' }).id('craftlin:mystical/xychorium/blue')
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_green', 8), ['XXX', 'XX ', '   '], { X: 'mysticalagriculture:xychorium_essence' }).id('craftlin:mystical/xychorium/green')
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_red', 8), ['   ', ' XX', 'XXX'], { X: 'mysticalagriculture:xychorium_essence' }).id('craftlin:mystical/xychorium/red')
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_dark', 8), ['XX ', 'XX ', 'X  '], { X: 'mysticalagriculture:xychorium_essence' }).id('craftlin:mystical/xychorium/dark')
    craftlin.shaped(Item.of('xycraft_world:xychorium_gem_light', 8), ['X  ', 'XX ', 'XX '], { X: 'mysticalagriculture:xychorium_essence' }).id('craftlin:mystical/xychorium/light')
    craftlin.shaped(Item.of('craftlin:draconium_ingot', 4), ['AAA', 'ABA', 'AAA'], { A: 'mysticalagriculture:draconium_2_essence', B: 'craftlin:draconium_ingot_dust' }).id('craftlin:mystical/draconium_ingots')
    craftlin.shaped(Item.of('ae2:silicon', 4), ['SSS', 'S S', 'SSS'], { S: 'mysticalagriculture:silicon_essence' })
})
console.log('Mystical Agriculture.js is loaded!')